const PRODUCTS = [
  { category: "Fruits", price: "$1", stocked: true, name: "Apple" },
  { category: "Fruits", price: "$1", stocked: true, name: "Dragonfruit" },
  { category: "Fruits", price: "$2", stocked: false, name: "Passionfruit" },
  { category: "Fruits", price: "$3", stocked: true, name: "Banana" },
  { category: "Fruits", price: "$2", stocked: true, name: "Orange" },
  { category: "Fruits", price: "$4", stocked: false, name: "Pineapple" },
  { category: "Fruits", price: "$1", stocked: true, name: "Strawberry" },
  { category: "Fruits", price: "$3", stocked: true, name: "Blueberry" },
  { category: "Fruits", price: "$2", stocked: false, name: "Papaya" },
  { category: "Fruits", price: "$5", stocked: true, name: "Mango" },
  { category: "Fruits", price: "$1", stocked: true, name: "Kiwi" },
  { category: "Fruits", price: "$3", stocked: false, name: "Pomegranate" },
  { category: "Fruits", price: "$2", stocked: true, name: "Grape" },
  { category: "Fruits", price: "$4", stocked: true, name: "Guava" },
  { category: "Fruits", price: "$1", stocked: false, name: "Lemon" },
  { category: "Vegetables", price: "$2", stocked: true, name: "Spinach" },
  { category: "Vegetables", price: "$4", stocked: false, name: "Pumpkin" },
  { category: "Vegetables", price: "$1", stocked: true, name: "Peas" },
  { category: "Vegetables", price: "$3", stocked: true, name: "Broccoli" },
  { category: "Vegetables", price: "$2", stocked: false, name: "Cauliflower" },
  { category: "Vegetables", price: "$1", stocked: true, name: "Carrot" },
  { category: "Vegetables", price: "$4", stocked: true, name: "Asparagus" },
  { category: "Vegetables", price: "$2", stocked: false, name: "Eggplant" },
  { category: "Vegetables", price: "$3", stocked: true, name: "Zucchini" },
  { category: "Vegetables", price: "$1", stocked: true, name: "Tomato" },
  { category: "Vegetables", price: "$5", stocked: false, name: "Artichoke" },
  { category: "Vegetables", price: "$2", stocked: true, name: "Cucumber" },
  { category: "Vegetables", price: "$3", stocked: true, name: "Bell Pepper" },
  { category: "Vegetables", price: "$4", stocked: false, name: "Beet" },
  { category: "Vegetables", price: "$1", stocked: true, name: "Radish" }
];

export default PRODUCTS;
